### ISSUE TITLE
Need TextFx 64 bit 

### ISSUE THREAD

**Issue by pop-dahaka** [HQJaTu/NPPTextFX#1]
Hi , 
Can you update TextFx for notepad plus 64 bit when you have some free time ?

Best Wishes .

**Comment by HQJaTu** [comment]
There exists an unreleased version, that I'm using myself. If you're prepared to use a plugin which may have sharp edges in it, I can push the code and binaries for it.

**Comment by pop-dahaka** [comment]
Do it please and release it , i need it .

Best Wishes .

**Comment by pop-dahaka** [comment]
i wish you still remember .

**Comment by HQJaTu** [comment]
There is a .dll added to source tree.
See: https://github.com/HQJaTu/NPPTextFX/tree/VS2017-x64/bin/x64

**Comment by pop-dahaka** [comment]
Thanks for your time and work , but there is a problem 
1) I downloaded the NppTextFX.dll file and put it @ npp.7.5.4.bin.x64\plugins 
2) using windows 7 X64 , run npp as admin and using Command Line Switches  -multiInst -nosession 
3) TextFX Tools checking T:+Sort ascending and also T:+Sort outputs only UNIQUE (at column) lines 
4) npp File Tabe --> Open the text file then pres Ctrl + A (select all lines) 
5) TextFX --> TextFX Tools --> T:Sort lines case sensitive (at column) 
6) error message appear "access violation" , attached TextFX 1.jpg
7) close npp giving those error "convertall-allocatedTextBufferSize" two times , attached TextFX 2.jpg
8) then error "Buffer write beyond end" , attached TextFX 3.jpg
9) then error "convertall-allocatedTextBufferSize"  two times 
10) then error "Buffer write beyond end" 

I wish you fix this soon when you have free time .

![textfx 1](https://user-images.githubusercontent.com/17509547/36115759-baefd8a0-103c-11e8-8377-e8127e3e5c0d.jpg)
![textfx 2](https://user-images.githubusercontent.com/17509547/36115760-bb358634-103c-11e8-8869-607f7cec0076.jpg)
![textfx 3](https://user-images.githubusercontent.com/17509547/36115762-bb6c239c-103c-11e8-8fd4-1cbee70fcd1c.jpg)

**Comment by HQJaTu** [comment]
You asked for an early version and that's what you got. Thanks for testing, though. There are ~140 separate functions in TextFX and I have not created unit tests for all of them yet.

If you really want to help, please create an issue for each separate bug you found there. I need to attack them one at a time and you bundling them into this one will not work for me. Based on your upcoming separate issues, I can prioritize my work towards them.

Since this issue was about missing binary file, I will resolve this one and wait for your new issues.

**Comment by pop-dahaka** [comment]
OK thanks , next time I'll create new issue for each bug . 
Update it please .

**Comment by HQJaTu** [comment]
As I said:
If you want to help, you need to start prioritizing my work by creating issues of things you want to get fixed. This one is closed an it stays that way, unfortunately I cannot start de-ciphering this single ticket having dozen issues packed into it.

**Comment by cup** [comment]
https://github.com/HQJaTu/NPPTextFX/issues/12
