### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Xaekai** [HQJaTu/NPPTextFX#17]
The link to the message about TextFX abandonment in the README is a broken link, as the docs subdomain of the NPP website no longer exists at all, and I can't seem to find elsewhere online either.

I was just trying to fulfill a curiosity about why the sources for 0.26 were never released. I suppose the only option I have left is to find a way to ask Chris Severance (@severach ???) myself.

**Comment by HQJaTu** [comment]
I don't think fixing obsoleted links in docs is a very high priority task.

What this project needs is an pair of C++ capable hands finalizing the parts I never did and fixing the bugs I created while making the code 64-bit compliant. Personally, I don't have that much time to contribute into this project.

**Comment by Xaekai** [comment]
It's not a high priority task. However it being a minor thing is **no reason to not do it**.

I came here explicitly on a quest for a modern compile of this plugin. But if such a simple patch as this is met with resistance, the only way I'd expend the effort further is at a hard-fork.

**Comment by severach** [comment]
I fixed the [TextFX](http://textfx.no-ip.com/textfx/) download link and added the entire history.

**Comment by Xaekai** [comment]
What a glorious day. I am gratified that sources that have been missing for over a decade are now available by side effect of my curiosity tangent.

Thank you @severach for acknowledging my ping. These files will be very helpful.

**Comment by HQJaTu** [comment]
@Xaekai feel free to take ownership of this project. I would be happy to hand it over to somebody who actually can take care of it. At the moment, I cannot.
