### ISSUE TITLE
Any compiled dlls available?

### ISSUE THREAD

**Issue by adam-jones-net** [HQJaTu/NPPTextFX#3]
I can't compile myself, are dlls available of it, ideally that work in the 64bit editor.

**Comment by yougg** [comment]
I need 64bit binary version too, can someone please help compile one?

**Comment by HQJaTu** [comment]
There is an issue regarding this. Already closed, it has the link https://github.com/HQJaTu/NPPTextFX/tree/VS2017-x64/bin/x64 in it.
