### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by MaltronCraft** [HQJaTu/NPPTextFX#6]
Hi, i just downloaded your plugin for NotePad++ and it said it was: Trojan:Win32/Spursint.F!cl file: C:\Program Files\Notepad++\plugins\NppTextFX\NppTextFX.dll and wont let me use it.
![image](https://user-images.githubusercontent.com/41383245/49488098-233ec100-f7fa-11e8-8498-60582f3d96a5.png)

**Comment by HQJaTu** [comment]
Which anti-virus was that? An obvious false positive given.

See: [Virustotal.com](https://www.virustotal.com/#/file/5954a0741d4c38913af3ea7e4e2f97695c174b9dba437db5b4ecb3d1a1b9c092/detection) for scan results.

**Comment by MaltronCraft** [comment]
Windows Defender. The system anti-virus.

**Comment by HQJaTu** [comment]
Oh man! :-(

**Comment by MaltronCraft** [comment]
Yeah, it just deletes it and won’t let me keep it.
